config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :phone_numbers, only: [:index, :create]

  root to: "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :phone_numbers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @phone_number = PhoneForm.new
  end
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController

  def new

  end

  def create
    @phone_number = PhoneForm.new phone_params
    if @phone_number.save
      redirect_to root_path, notice: "Phone numbers saved"
    else
      redirect_to root_path, notice: "Something went wrong"
    end
  end

  def edit

  end

  def update

  end

  private

    def phone_params
      params.require(:phone_form).permit(:username, phone_numbers:[])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= bootstrap_flash %> 
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="container">
  <h1>Add Phone Numbers</h1>

  <%= bootstrap_form_for @phone_number, url: phone_numbers_path do |f| %>
    <%= f.text_field :username %>
    <%= f.text_field :phone_numbers, name: "phone_form[phone_numbers][]" %>
    <%= f.text_field :phone_numbers, name: "phone_form[phone_numbers][]" %>
    <%= f.text_field :phone_numbers, name: "phone_form[phone_numbers][]" %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/phone_numbers/index.html.erb
Main